Print diffs for test failures
Vendor my ztest diff library in here, so we don't add a dependency. This gives
much nicer test failures:

    --- FAIL: TestScript (0.00s)
        --- FAIL: TestScript/watch-dir/bug-277 (0.96s)
            helpers_test.go:1021:

                --- have
                +++ want
                @@ -1,6 +1,5 @@
                      RENAME   /apple
                            REMOVE   /pear
                            REMOVE   /foo
                -have       CREATE   /pear ← /apple
                            CREATE   /foo
                            CREATE   /apple

Instead of:

    --- FAIL: TestScript (0.00s)
        --- FAIL: TestScript/watch-dir/bug-277 (0.96s)
            helpers_test.go:1020:
                have:
                    CREATE   /foo
                    REMOVE   /foo
                    CREATE   /apple
                    RENAME   /apple
                    CREATE   /pear ← /apple
                    REMOVE   /pear
                want:
                    CREATE   /foo
                    REMOVE   /foo
                    CREATE   /apple
                    RENAME   /apple
                    REMOVE   /pear
    FAIL