Add "repeat" command
Useful for some of the flaky tests; I noticed that some tests are
somewhat flaky on my laptop – not sure if that's a new thing due to
changes on Linux or fsnotify, or if it was always like that. But I don't
recall these failing before and I spent a lot of time eliminating flaky
tests in the past 🤔

Not using it anywhere yet, useful for later.

	% uname -a
	Linux x13.arp242.net 6.19.13_1 #1 SMP PREEMPT_DYNAMIC Fri Apr 24 01:14:51 UTC 2026 x86_64 GNU/Linux

	% repeat 5; go test
	PASS
	ok      github.com/fsnotify/fsnotify    9.804s
	PASS
	ok      github.com/fsnotify/fsnotify    10.293s
	--- FAIL: TestScript (0.00s)
	    --- FAIL: TestScript/watch-dir/watch-file-inside-watched-dir (0.70s)
		helpers_test.go:1030:
		    have:
			CREATE   /file
			WRITE    /file
			CHMOD    /file
			REMOVE   /file
		    want:
			CREATE   /file
			WRITE    /file
			WRITE    /file
			CHMOD    /file
			REMOVE   /file
		    diff:
			--- have
			+++ want
			@@ -2,3 +2,4 @@
				CREATE   /file
				REMOVE   /file
				WRITE    /file
			+want   WRITE    /file
	    --- FAIL: TestScript/watch-dir/only-remove (1.51s)
		helpers_test.go:1030:
		    have:

		    want:
			REMOVE   /file
			REMOVE   /link
			REMOVE   /dir
		    diff:
			--- have
			+++ want
			@@ -1 +1,3 @@
			-have
			+want REMOVE   /dir
			+want   REMOVE   /file
			+want   REMOVE   /link
	FAIL
	exit status 1
	FAIL    github.com/fsnotify/fsnotify    9.826s
	PASS
	ok      github.com/fsnotify/fsnotify    9.984s
	--- FAIL: TestScript (0.00s)
	    --- FAIL: TestScript/watch-dir/watch-dir-inside-watched (0.86s)
		helpers_test.go:1030:
		    have:
			CREATE   /dir
			CREATE   /dir/two
			WRITE    /dir/two
			REMOVE   /dir/two
		    want:
			CREATE   /dir
			CREATE   /one
			WRITE    /one
			CREATE   /dir/two
			WRITE    /dir/two
			REMOVE   /one
			REMOVE   /dir/two
		    diff:
			--- have
			+++ want
			@@ -1,4 +1,7 @@
			      CREATE   /dir
				CREATE   /dir/two
			+want   CREATE   /one
				REMOVE   /dir/two
			+want   REMOVE   /one
				WRITE    /dir/two
			+want   WRITE    /one
	FAIL
	exit status 1
	FAIL    github.com/fsnotify/fsnotify    9.586s